name: dalatorder
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.1.4
  flutter_svg: ^0.22.0
  firebase_core: ^1.2.0
  flutter_facebook_login: ^3.0.0
#  firebase_auth: ^1.1.3
  fluttertoast: ^8.0.6
#  firebase_database: ^6.1.2
  lottie: any
  image_picker: ^0.7.4
#  firebase_storage: ^8.0.5
  permission_handler: ^7.1.0
  carousel_slider: ^3.0.0
  curved_navigation_bar: ^0.3.7
  dio: ^4.0.0
#  google_maps_flutter: ^2.0.3
  geolocator: ^7.0.3
  badges: ^1.2.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

